export const fieldKeywords = {
  nameColumn: [
    "name",
    "med",
    "medicine",
    "drug",
    "item",
    "product",
    "description",
    "med_name",
  ],
  qtyColumn: [
    "qty",
    "quantity",
    "stock",
    "unit",
    "units",
    "count",
    "on hand",
    "available",
    "balance",
  ],
  expiryColumn: ["expiry", "exp", "date", "valid"],
  priceColumn: [
    "price",
    "rate",
    "cost",
    "inr",
    "purchase rate",
    "buy price",
    "mrp",
    "retail",
    "selling",
  ],
  batchColumn: ["batch", "lot", "no", "code"],
  barcodeColumn: ["barcode", "upc", "ean", "sku"],
  categoryColumn: ["category", "cat", "type", "group", "classification"],
  manufacturerColumn: [
    "manufacturer",
    "mfr",
    "maker",
    "brand",
    "company",
    "vendor",
  ],
  genericNameColumn: ["generic", "gen", "salt", "composition"],
  strengthColumn: ["strength", "mg", "ml", "dose", "concentration"],
  dosageFormColumn: ["dosage", "form", "type", "drug_form"],
  hsnCodeColumn: ["hsn", "hsn_code", "hsncode", "sac", "tariff"],
  scheduleColumn: [
    "schedule",
    "regulatory",
    "regulatory_classification",
    "drug_schedule",
  ],
  gstPercentageColumn: ["gst", "gst%", "tax", "tax_percent"],
};

export const fieldExcludes = {
  nameColumn: [
    "generic",
    "price",
    "rate",
    "cost",
    "qty",
    "quantity",
    "stock",
    "expiry",
    "date",
    "batch",
    "barcode",
    "sku",
  ],
  qtyColumn: [
    "price",
    "rate",
    "cost",
    "inr",
    "date",
    "expiry",
    "name",
    "med",
    "batch",
    "barcode",
    "sku",
  ],
  expiryColumn: ["name", "med", "price", "qty", "batch", "barcode", "sku"],
  priceColumn: [
    "qty",
    "quantity",
    "stock",
    "units",
    "count",
    "name",
    "med",
    "expiry",
    "date",
    "batch",
    "barcode",
    "sku",
  ],
  batchColumn: [
    "name",
    "med",
    "price",
    "qty",
    "expiry",
    "date",
    "barcode",
    "hsn",
  ],
  barcodeColumn: ["name", "med", "price", "qty", "expiry", "date", "batch"],
  categoryColumn: [
    "name",
    "med",
    "price",
    "qty",
    "expiry",
    "date",
    "batch",
    "barcode",
    "generic",
  ],
  manufacturerColumn: [
    "name",
    "med",
    "price",
    "qty",
    "expiry",
    "date",
    "batch",
    "barcode",
    "generic",
    "category",
  ],
  genericNameColumn: [
    "name",
    "med",
    "price",
    "qty",
    "expiry",
    "date",
    "batch",
    "barcode",
  ],
  strengthColumn: [
    "name",
    "med",
    "price",
    "qty",
    "expiry",
    "date",
    "batch",
    "barcode",
  ],
  dosageFormColumn: [
    "name",
    "med",
    "price",
    "qty",
    "expiry",
    "date",
    "batch",
    "barcode",
  ],
  hsnCodeColumn: [
    "name",
    "med",
    "price",
    "qty",
    "expiry",
    "date",
    "batch",
    "barcode",
  ],
  scheduleColumn: [
    "name",
    "med",
    "price",
    "qty",
    "quantity",
    "stock",
    "expiry",
    "date",
    "batch",
    "barcode",
    "category",
    "manufacturer",
    "generic",
  ],
  gstPercentageColumn: [
    "name",
    "med",
    "price",
    "qty",
    "expiry",
    "date",
    "batch",
    "barcode",
  ],
};

export const fieldOrder = [
  "nameColumn",
  "qtyColumn",
  "expiryColumn",
  "priceColumn",
  "batchColumn",
  "barcodeColumn",
  "categoryColumn",
  "manufacturerColumn",
  "genericNameColumn",
  "strengthColumn",
  "dosageFormColumn",
  "scheduleColumn",
  "hsnCodeColumn",
  "gstPercentageColumn",
];
