export const SubscriptionStatus = Object.freeze({
  TRIAL: "TRIAL",
  ACTIVE: "ACTIVE",
  PENDING: "PENDING",
  GRACE_PERIOD: "GRACE_PERIOD",
  EXPIRED: "EXPIRED",
  SUSPENDED: "SUSPENDED",
  CANCELLED: "CANCELLED",
});

export const PaymentStatus = Object.freeze({
  CREATED: "CREATED",
  INITIATED: "INITIATED",
  PENDING: "PENDING",
  AUTHORIZED: "AUTHORIZED",
  CAPTURED: "CAPTURED",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  EXPIRED: "EXPIRED",
  CANCELLED: "CANCELLED",
  REFUNDED: "REFUNDED",
  PARTIALLY_REFUNDED: "PARTIALLY_REFUNDED",
  RECONCILING: "RECONCILING",
  RECOVERY_PENDING: "RECOVERY_PENDING",
  PARTIALLY_PAID: "PARTIALLY_PAID",
  REVERSED: "REVERSED",
});

export const Role = Object.freeze({
  OWNER: "OWNER",
  STAFF: "STAFF",
  ADMIN: "ADMIN",
  PHARMACIST: "PHARMACIST",
  CASHIER: "CASHIER",
});

export const PurchaseOrderStatus = Object.freeze({
  DRAFT: "DRAFT",
  PENDING_APPROVAL: "PENDING_APPROVAL",
  APPROVED: "APPROVED",
  SENT: "SENT",
  PARTIALLY_RECEIVED: "PARTIALLY_RECEIVED",
  RECEIVED: "RECEIVED",
  RECONCILED: "RECONCILED",
  CANCELLED: "CANCELLED",
});

export const MedicineStatus = Object.freeze({
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  DISCONTINUED: "DISCONTINUED",
  BLOCKED: "BLOCKED",
  RESTRICTED: "RESTRICTED",
  RECALLED: "RECALLED",
});

export const SupplierStatus = Object.freeze({
  ACTIVE: "ACTIVE",
  SUSPENDED: "SUSPENDED",
  INACTIVE: "INACTIVE",
  BLOCKED: "BLOCKED",
  BLACKLISTED: "BLACKLISTED",
  ARCHIVED: "ARCHIVED",
});

export const SupplierType = Object.freeze({
  WHOLESALER: "WHOLESALER",
  MANUFACTURER: "MANUFACTURER",
  DISTRIBUTOR: "DISTRIBUTOR",
  LOCAL_VENDOR: "LOCAL_VENDOR",
});

export const StockAlertType = Object.freeze({
  LOW_STOCK: "LOW_STOCK",
  OUT_OF_STOCK: "OUT_OF_STOCK",
  EXPIRING: "EXPIRING",
  EXPIRED: "EXPIRED",
  RECALLED: "RECALLED",
  OVERSTOCK: "OVERSTOCK",
  PROCUREMENT_DELAY: "PROCUREMENT_DELAY",
});

export const AlertStatus = Object.freeze({
  ACTIVE: "ACTIVE",
  SNOOZED: "SNOOZED",
  ACKNOWLEDGED: "ACKNOWLEDGED",
  RESOLVED: "RESOLVED",
  ESCALATED: "ESCALATED",
  ON_ORDER: "ON_ORDER",
});

export const AuditLogType = Object.freeze({
  SECURITY: "SECURITY",
  INVENTORY: "INVENTORY",
  FINANCIAL: "FINANCIAL",
  SYSTEM: "SYSTEM",
  ACCESS: "ACCESS",
});

export const RecallSeverity = Object.freeze({
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
});

export const AdminRole = Object.freeze({
  ROOT_ADMIN: "ROOT_ADMIN",
  ADMIN: "ADMIN",
  SUPPORT: "SUPPORT",
  SALES: "SALES",
  FINANCE: "FINANCE",
});

export const AdminAuditAction = Object.freeze({
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_SUSPENDED: "USER_SUSPENDED",
  USER_ACTIVATED: "USER_ACTIVATED",
  USER_BLOCKED: "USER_BLOCKED",
  USER_DELETED: "USER_DELETED",
  USER_PASSWORD_RESET: "USER_PASSWORD_RESET",
  USER_DEVICE_RESET: "USER_DEVICE_RESET",
  SHOP_CREATED: "SHOP_CREATED",
  SHOP_UPDATED: "SHOP_UPDATED",
  SHOP_APPROVED: "SHOP_APPROVED",
  SHOP_SUSPENDED: "SHOP_SUSPENDED",
  SHOP_BLACKLISTED: "SHOP_BLACKLISTED",
  SHOP_DELETED: "SHOP_DELETED",
  SUBSCRIPTION_CREATED: "SUBSCRIPTION_CREATED",
  SUBSCRIPTION_EXTENDED: "SUBSCRIPTION_EXTENDED",
  SUBSCRIPTION_UPGRADED: "SUBSCRIPTION_UPGRADED",
  SUBSCRIPTION_DOWNGRADED: "SUBSCRIPTION_DOWNGRADED",
  SUBSCRIPTION_CANCELLED: "SUBSCRIPTION_CANCELLED",
  SUBSCRIPTION_RENEWED: "SUBSCRIPTION_RENEWED",
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
  PAYMENT_REFUNDED: "PAYMENT_REFUNDED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  DEVICE_BLOCKED: "DEVICE_BLOCKED",
  DEVICE_UNBLOCKED: "DEVICE_UNBLOCKED",
  FEATURE_FLAG_TOGGLED: "FEATURE_FLAG_TOGGLED",
  BROADCAST_SENT: "BROADCAST_SENT",
  ADMIN_LOGIN: "ADMIN_LOGIN",
  ADMIN_LOGOUT: "ADMIN_LOGOUT",
});
