export const SubscriptionStatus = Object.freeze({
  TRIAL: "TRIAL",
  ACTIVE: "ACTIVE",
  PENDING: "PENDING",
  GRACE_PERIOD: "GRACE_PERIOD",
  EXPIRED: "EXPIRED",
  SUSPENDED: "SUSPENDED",
  CANCELLED: "CANCELLED",
});
